// const cities=['New York, NY','Los Angeles, CA','Chicago, IL',  'Dallas, TX','Houston, TX', 'Washington, DC', 
// 'Miami, FL',  'Philadelphia, PA', 'Atlanta, GA', 'Boston, MA', 'Phoenix, AZ', 
// 'San Francisco, CA', 'Riverside, CA', 'Detroit, MI',
// 'Seattle, WA', 'Minneapolis, MN', 'San Diego, CA', 'Tampa, FL', 'Denver, CO',
//  'St Louis, MO', 'Baltimore, MD',
// 'Orlando, FL', 'Charlotte, NC', 'San Antonio, TX', 'Portland, OR', 
// 'Sacramento, CA', 'Pittsburgh, PA', 'Las Vegas, NV',
// 'Cincinnati, OH', 'Austin, TX']

export const cityOptions = [
    { key: 'New York, NY', text: 'New York, NY', value: 'New York, NY' },
    { key: 'Los Angeles, CA', text: 'Los Angeles, CA', value: 'Los Angeles, CA' },
    { key: 'Chicago, IL', text: 'Chicago, IL', value: 'Chicago, IL' },
    { key: 'Dallas, TX', text: 'Dallas, TX', value: 'Dallas, TX' },
    { key: 'Houston, TX', text: 'Houston, TX', value: 'Houston, TX' },
    { key: 'Washington, DC', text: 'Washington, DC', value: 'Washington, DC' },
    { key: 'Miami, FL', text: 'Miami, FL', value: 'Miami, FL' },
    { key: 'Philadelphia, PA', text: 'Philadelphia, PA', value: 'Philadelphia, PA' },
    { key: 'Atlanta, GA', text: 'Atlanta, GA', value: 'Atlanta, GA' },
    { key: 'Boston, MA', text: 'Boston, MA', value: 'Boston, MA' },
    { key: 'Phoenix, AZ', text: 'Phoenix, AZ', value: 'Phoenix, AZ' },
    { key: 'San Francisco, CA', text: 'San Francisco, CA', value: 'San Francisco, CA' },
    { key: 'Riverside, CA', text: 'Riverside, CA', value: 'Riverside, CA' },
    { key: 'Detroit, MI', text: 'Detroit, MI', value: 'Detroit, MI' },
    { key: 'Seattle, WA', text: 'Seattle, WA', value: 'Seattle, WA' },
    { key: 'Minneapolis, MN', text: 'Minneapolis, MN', value: 'Minneapolis, MN' },
    { key: 'San Diego, CA', text: 'San Diego, CA', value: 'San Diego, CA' },
    { key: 'Tampa, FL', text: 'Tampa, FL', value: 'Tampa, FL' },
    { key: 'Denver, CO', text: 'Denver, CO', value: 'Denver, CO' },
    { key: 'St Louis, MO', text: 'St Louis, MO', value: 'St Louis, MO' },
    { key: 'Baltimore, MD', text: 'Baltimore, MD', value: 'Baltimore, MD' },
    { key: 'Orlando, FL', text: 'Orlando, FL', value: 'Orlando, FL' },
    { key: 'Charlotte, NC', text: 'Charlotte, NC', value: 'Charlotte, NC' },
    { key: 'San Antonio, TX', text: 'San Antonio, TX', value: 'San Antonio, TX' },
    { key: 'Portland, OR', text: 'Portland, OR', value: 'Portland, OR' },
    { key: 'Sacramento, CA', text: 'Sacramento, CA', value: 'Sacramento, CA' },
    { key: 'Pittsburgh, PA', text: 'Pittsburgh, PA', value: 'Pittsburgh, PA' },
    { key: 'Las Vegas, NV', text: 'Las Vegas, NV', value: 'Las Vegas, NV' },
    { key: 'Cincinnati, OH', text: 'Cincinnati, OH', value: 'Cincinnati, OH' },
    { key: 'Austin, TX', text: 'Austin, TX', value: 'Austin, TX' }
  ]